apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: ks-sample-pro
  name: ks-sample-pro
  namespace: work001
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30961
  selector:
    app: kubesphere
    component: ks-sample-pro
    tier: backend
  sessionAffinity: None
  type: NodePort